PredavacWebApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PredavacWebApplication.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Osnovne informacije o nama.";

            return View();
        }
        public ActionResult Contact()
        {
            ViewBag.Message = "Ukoliko imate problema s aplikacijom možete nas pronaći " +
                              "na navedenoj adresi ili nas kontaktirati putem navedenih" +
                              " e-mailova";

            return View();
        }
    }
}

PredavacWebApplication/Controllers/KolegijsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Data.Entity;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PredavacWebApplication.Models;

namespace PredavacWebApplication.Controllers
{
    public class KolegijsController : Controller
    {
        private KolegijDBContext db = new KolegijDBContext();

        // GET: Kolegijs
        public ActionResult Index()
        {
            return View(db.Kolegij.ToList());
        }

        // GET: Kolegijs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kolegij kolegij = db.Kolegij.Find(id);
            if (kolegij == null)
            {
                return HttpNotFound();
            }
            return View(kolegij);
        }

        // GET: Kolegijs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Kolegijs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Naziv,Nositelj,StudijskaGod")] Kolegij kolegij)
        {
            if (ModelState.IsValid)
            {
                db.Kolegij.Add(kolegij);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kolegij);
        }

        // GET: Kolegijs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kolegij kolegij = db.Kolegij.Find(id);
            if (kolegij == null)
            {
                return HttpNotFound();
            }
            return View(kolegij);
        }

        // POST: Kolegijs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Naziv,Nositelj,StudijskaGod")] Kolegij kolegij)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kolegij).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kolegij);
        }

        // GET: Kolegijs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kolegij kolegij = db.Kolegij.Find(id);
            if (kolegij == null)
            {
                return HttpNotFound();
            }
            return View(kolegij);
        }

        // POST: Kolegijs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kolegij kolegij = db.Kolegij.Find(id);
            db.Kolegij.Remove(kolegij);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult SearchIndex(string Naziv, string searchString)
        {

            //prazna lista za nazive gdje cemo staviti nazive iz baze
            var listaZaKolegij = new List<string>();

            //upit na bazu gdje dohvacamo nazive
            var nazivIzBaze = db.Kolegij.Select(x => x.Naziv).OrderBy(x => x);

            //napuniti praznu listu s razlicitim vrijednostima iz baze
            listaZaKolegij.AddRange(nazivIzBaze.Distinct());

            //prikazati listu na html stranici
            ViewBag.Naziv = new SelectList(listaZaKolegij);

            // moramo dohvatiti sve nazive iz baze
            // OVO JE NAJBITNIJE
            /*
             pomocu linq-a napravimo inner join te povezemo dvije tablice po odgovarajucem kljucu, a nakon toga
             dohvatimo polja koja nam trebaju i stavimo u viewModel
            
            viewModel predstavlja poseban model koji ne postoji u bazi, vec se sastoji od razlicitih polja iz vise modela u bazi, koristi se kada se korisniku treba prikazati 
            nesto iz vise tablica  

            Imajte na umu da je ovo INNER JOIN sto znaci da svaki kolegij mora imati predavaca kako bi dohvatio novi kolegijPredavacViewModel 
             */
            var kolegijPredavacViewModel = db.Kolegij
                .Join(db.Predavac, kolegij => kolegij.Id, predavac => predavac.KolegijId,
                    (kolegij, predavac) => new {kolegij, predavac})
                .Select(rezultat =>
                    new KolegijPredavacViewModel
                    {
                        Id = rezultat.kolegij.Id,
                        Naziv = rezultat.kolegij.Naziv,
                        Nositelj = rezultat.kolegij.Nositelj,
                        StudijskaGod = rezultat.kolegij.StudijskaGod,
                        Datum =  rezultat.predavac.Datum,
                        Ime = rezultat.predavac.Ime,
                        Prezime = rezultat.predavac.Prezime,
                        Tema = rezultat.predavac.Tema
                    }).ToList();


            // provjeriti je li string prazan i naci kolegije s tim nazivom
            if (!string.IsNullOrWhiteSpace(searchString))
            {
                kolegijPredavacViewModel = kolegijPredavacViewModel.Where(x => x.Prezime.Contains(searchString)).ToList();
            }

            //provjera je li je odabran naziv i pretrazivanje po nazivu
            if (!string.IsNullOrWhiteSpace(Naziv))
            {
                kolegijPredavacViewModel = kolegijPredavacViewModel.Where(x => x.Naziv == Naziv).ToList();
            }

            // vratiti nadene kolegije na html formu
            return View(kolegijPredavacViewModel);
        }

        public ActionResult _KolegijPredavac(int? KolegijId)
        {
            if (KolegijId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IEnumerable<Predavac> Predavac = db.Predavac.Where(x => x.KolegijId == KolegijId);


            return PartialView(Predavac);
        }
        }
}

PredavacWebApplication/Controllers/PredavacsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PredavacWebApplication.Models;

namespace PredavacWebApplication.Controllers
{
    public class PredavacsController : Controller
    {
        private KolegijDBContext db = new KolegijDBContext();

        // GET: Predavacs
        public ActionResult Index()
        {
            var predavac = db.Predavac.Include(p => p.Kolegij);
            return View(predavac.ToList());
        }

        // GET: Predavacs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Predavac predavac = db.Predavac.Find(id);
            if (predavac == null)
            {
                return HttpNotFound();
            }
            return View(predavac);
        }

        // GET: Predavacs/Create
        public ActionResult Create()
        {
            ViewBag.KolegijId = new SelectList(db.Kolegij, "Id", "Naziv");
            return View();
        }

        // POST: Predavacs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Ime,Prezime,Tema,Datum,BrStudent,KolegijId")] Predavac predavac)
        {
            if (ModelState.IsValid)
            {
                db.Predavac.Add(predavac);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.KolegijId = new SelectList(db.Kolegij, "Id", "Naziv", predavac.KolegijId);
            return View(predavac);
        }

        // GET: Predavacs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Predavac predavac = db.Predavac.Find(id);
            if (predavac == null)
            {
                return HttpNotFound();
            }
            ViewBag.KolegijId = new SelectList(db.Kolegij, "Id", "Naziv", predavac.KolegijId);
            return View(predavac);
        }

        // POST: Predavacs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Ime,Prezime,Tema,Datum,BrStudent,KolegijId")] Predavac predavac)
        {
            if (ModelState.IsValid)
            {
                db.Entry(predavac).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.KolegijId = new SelectList(db.Kolegij, "Id", "Naziv", predavac.KolegijId);
            return View(predavac);
        }

        // GET: Predavacs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Predavac predavac = db.Predavac.Find(id);
            if (predavac == null)
            {
                return HttpNotFound();
            }
            return View(predavac);
        }

        // POST: Predavacs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Predavac predavac = db.Predavac.Find(id);
            db.Predavac.Remove(predavac);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PredavacWebApplication/Views/Home/About.cshtml
@{
    ViewBag.Title = "O nama";
}
<br />
<br />
<br />
<br />
<br />
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Studenti 3. godine smjera Poslovna informatika:<br>
             Nikolina Raguž<br>
             Vedran Šagodić
    </p>

PredavacWebApplication/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Kontakt";
}

<br />
<br />
<br />
<br />
<br />
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Gajev Trg 7<br />
    31000 Osijek<br />
    Hrvatska<br />
    <abbr title="Telefon">Tel:</abbr>
    +385(0)31 200-211
</address>

<address>
    <strong>Podrška:</strong>   <a href="mailto:vedran.sagodic@gmail.com">vedran.sagodic@gmail.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:raguz.nikolina@gmail.com">raguz.nikolina@gmail.com</a>
</address>

PredavacWebApplication/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Početna stranica";
}
<br />
<br />
<div class="jumbotron">
    <br />
    <br />
    <div id="mycarousel" class="carousel slide" data-ride="carousel" style="margin-top:-10px">
        <ol class="carousel-indicators">
            <li data-target="#mycarousel" data-slide-to="0" class="active"></li>
            <li data-target="#mycarousel" data-slide-to="1"></li>
            <li data-target="#mycarousel" data-slide-to="2"></li>
            <li data-target="#mycarousel" data-slide-to="3"></li>
            <li data-target="#mycarousel" data-slide-to="4"></li>
            <li data-target="#mycarousel" data-slide-to="5"></li>
            <li data-target="#mycarousel" data-slide-to="6"></li>
        </ol>

        <div class="carousel-inner" role="listbox">
            <div class="item active" align="center">
                <img src="~/Content/slika/054c8748-196f-449b-c465-e04f634fc248.jpeg" width="600" height="400" />
                <div class="carousel-caption">
                </div>
            </div>

            <div class="item" align="center">
                <img src="~/Content/slika/13103475_1045723495481808_594197613660887786_n.jpg" width="600" height="400" />
                <div class="carousel-caption">
                </div>
            </div>

            <div class="item" align="center">
                <img src="~/Content/slika/13055340_1045725212148303_6116360199651222494_n.jpg" width="600" height="400" />
                <div class="carousel-caption">
                </div>
            </div>

            <div class="item" align="center">
                <img src="~/Content/slika/13083133_1045725008814990_8014669083671771373_n.jpg" width="600" height="400" />
                <div class="carousel-caption">
                </div>
            </div>

            <div class="item" align="center">
                <img src="~/Content/slika/13103475_1045723495481808_594197613660887786_n.jpg" width="600" height="400" />
                <div class="carousel-caption">
                </div>
            </div>

            <div class="item" align="center">
                <img src="~/Content/slika/13124450_1045724158815075_7957540489838149730_n.jpg" width="600" height="400" />
                <div class="carousel-caption">
                </div>
            </div>

            <div class="item" align="center">
                <img src="~/Content/slika/13124882_1045723758815115_5085482104490692124_n.jpg" width="600" height="400" />
                <div class="carousel-caption">
                </div>
            </div>

        </div>

        <a class="left carousel-control" href="#mycarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>

        <a class="right carousel-control" href="#mycarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>


    </div>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    </div>
<div style="text-align:center">
    <span class="dot"></span>
    <span class="dot"></span>
    <span class="dot"></span>
</div>
    <h1><center>Ekonomski fakultet u Osijeku
    <br />
        Gosti predavači na kolegijima</center></h1>
    <p class="lead">
</div>

<br />
<br />
<br />

    <h2><center>Kolegiji i gosti predavači</center></h2>
    <p><center>
    <justify>
        U web aplikaciji za evidenciju gostiju predavača po kolegijima
        možemo dodavati, pregledavati, pretraživati i uređivati popis gostiju predavača
        koji su održali predavanja na pojedinim kolegijima na Ekonomskom fakultetu u Osijeku.
    </justify></center></p>

<br />
<br />


    <div class="col-md-4">
        <h2><center>Unos kolegija</center></h2>
        <p><justify>
            Ovdje možete unijeti naziv kolegija na kojem je gostovao predavač,
            te nositelja kolegija i studijsku godinu na kojem se kolegij održava.
            <br />
               <center><img src="~/Content/slika/Google-Day-EFOS-1.png" height="200" width="200" /></center>
        </justify></p><br />
        <p><center>@Html.ActionLink("Popis Kolegija", "Index", "Kolegijs", null, new { @class = "btn btn-success btn-lg" })</center></p>
    </div>

<div class="col-md-4">
    <h2><center>Unos predavača</center></h2>
    <p>
        <justify>
            Unesite ime,prezime,datum i broj studenata koji su nazočili predavanju. <br />
            <center><img src="~/Content/slika/Rimac-04.png" height="200" width="200" /></center>
        </justify>
    </p>
    <br />
    <br />
    <i>Napomena:</i> <br />
    Kod unosa nadolazećeg predavanja u polje "Broj Prisutnih Studenata" upišite broj 0,
    a nakon predavanja upišite konačan broj studenata koji su prisustvovali predavanju.
    </p>
    <p><center>@Html.ActionLink("Popis predavača", "Index", "Predavacs", null, new { @class = "btn btn-success btn-lg" })</center></p>
</div>

    <div class="row">
        <div class="col-md-4">
        <h2><center>Tražilica</center></h2>
        <p><justify>
            Uz pomoć tražilice možete pretraživati predavače koji su gostovali na kolegijima. <br />
               <center><img src="~/Content/slika/Search-button.png" height="200" width="200" /></center>
        </justify></p>
        <p><center>@Html.ActionLink("Tražilica", "SearchIndex", "Kolegijs", null, new { @class = "btn btn-success btn-lg" })</center></p>
    </div>

</div>